name: Latest Stack Overflow Activity
on:
  schedule:
    # Runs at 00:00 midnight everyday
    - cron: '0 0 * * *'
  workflow_dispatch:
  
jobs:
  update-readme-with-stack-overflow:
    name: Update this repo's README with latest activity from StackOverflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "STACKOVERFLOW"
          commit_message: "Updated readme.md file with the latest Stack Overflow data for the user 12210908"
          feed_list: "https://stackoverflow.com/feeds/user/12210908"
          max_post_count: 5
